apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "sidecar-injector.fullname" . }}
  labels:
    {{- include "sidecar-injector.selectorLabels" . | nindent 8 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "sidecar-injector.fullname" . }}
subjects:
- kind: ServiceAccount
  name:  {{ include "sidecar-injector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
