apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sidecar-injector.fullname" . }}
  labels:
    {{- include "sidecar-injector.labels" . | nindent 4 }}
data:
  sidecarconfig.yaml: |-
{{ tpl (.Files.Get "data/sidecarconfig.yaml") . | indent 4 }}
