{{- $caCrt := .Values.certificate.caCrt }}
{{- $tlsCrt := .Values.certificate.tlsCrt }}
{{- $tlsKey := .Values.certificate.tlsKey }}
{{- if .Values.certificate.generate }}
{{- if or (not $caCrt) (not $tlsCrt) (not $tlsKey) }}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace (printf "%s" (include "sidecar-injector.certificateSecretName" $)) ) }}
{{- if $secret }}
{{- $tlsCrt = index $secret.data "tls.crt" }}
{{- $tlsKey = index $secret.data "tls.key" }}
{{- $caCrt = index $secret.data "ca.crt" }}
{{- else -}}
{{- $ca := genCA (printf "%s-ca" .Release.Namespace) 3650 }}
{{- $svcName := include "sidecar-injector.fullname" . }}
{{- $cn := printf "%s.%s.svc" $svcName .Release.Namespace }}
{{- $altName1 := printf "%s.cluster.local" $cn }}
{{- $altName2 := printf "%s" $cn }}
{{- $server := genSignedCert $cn nil (list $altName1 $altName2) 365 $ca }}
{{- $tlsCrt = b64enc $server.Cert }}
{{- $tlsKey = b64enc $server.Key }}
{{- $caCrt =  b64enc $ca.Cert }}
{{- end -}}
{{- end -}}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "sidecar-injector.certificateSecretName" . }}
  labels:
    {{- include "sidecar-injector.labels" . | nindent 4 }}
data:
  tls.crt: {{ $tlsCrt }}
  tls.key: {{ $tlsKey }}
  ca.crt:  {{ $caCrt }}
---
{{- end -}}


apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "sidecar-injector.fullname" . }}
webhooks:
  - name: {{ include "sidecar-injector.fullname" . }}.impart.security
    admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: {{ include "sidecar-injector.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /inject
      caBundle: {{ $caCrt }}
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["v1"]
        resources:
          - pods
    failurePolicy: Fail
    sideEffects: None
    objectSelector:
      matchLabels:
        {{ .Values.webhookinjector.objectSelectorLabel }}: enabled

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sidecar-injector.fullname" . }}
  labels:
    {{- include "sidecar-injector.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sidecar-injector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if $caCrt }}
        checksum/webhook-tls-config: {{ $caCrt | sha256sum }}
        {{- end }}
        tls.crt: {{ $tlsCrt }}
        tls.key: {{ $tlsKey }}
        ca.crt:  {{ $caCrt }}
      labels:
        {{- include "sidecar-injector.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sidecar-injector.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.webhookinjector.image.repository }}"
          imagePullPolicy: {{ .Values.webhookinjector.image.pullPolicy }}
          args:
          - --sidecar-config-file=/etc/webhook/config/sidecarconfig.yaml
          - --tls-cert-file=/etc/webhook/certs/tls.crt
          - --tls-private-key-file=/etc/webhook/certs/tls.key
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /etc/webhook/config
            name: webhook-config
          - name: certs
            mountPath: /etc/webhook/certs
            readOnly: true
          {{- if .Values.webhookinjector.additionalVolumeMounts }}
            {{- toYaml .Values.webhookinjector.additionalVolumeMounts | nindent 10 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "sidecar-injector.serviceAccountName" . }}
      volumes:
      - name: certs
        secret:
          secretName: {{ include "sidecar-injector.certificateSecretName" . }}
      - configMap:
          name: {{ include "sidecar-injector.fullname" . }}
        name: webhook-config
      {{- if .Values.webhookinjector.additionalVolumes }}
        {{- toYaml .Values.webhookinjector.additionalVolumes | nindent 6 }}
      {{- end }}
