apiVersion: v1
kind: Service
metadata:
  name: {{ include "sidecar-injector.fullname" . }}
  labels:
    {{- include "sidecar-injector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookinjector.service.type }}
  ports:
    - port: {{ .Values.webhookinjector.service.port }}
      targetPort: {{ .Values.webhookinjector.service.targetPort }}
  selector:
    {{- include "sidecar-injector.selectorLabels" . | nindent 4 }}
